### ISSUE TITLE
This repo is private

### ISSUE THREAD

**Issue by jpivarski** [iris-hep/as-user-facing#4]
@PerilousApricot (Andrew Melo) wants to add a user story but can't access it.

**Comment by gordonwatts** [comment]
Crap!! Sorry. I've fixed that. Sorry - private default keeps tripping me up!

**Comment by cranmer** [comment]
I'm trying to push my user-stories, but I don't have permission. 
@gordonwatts can you add several of us as collaborators to this repo?
